services:
  stock-database:
    image: mysql:8.4
    container_name: stock-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_db
      MYSQL_USER: stock_user
      MYSQL_PASSWORD: stock_pass
    ports:
      - "3307:3306"
    volumes:
      - stock-db-data:/var/lib/mysql
    networks:
      - microservices-net

  sales-database:
    image: mysql:8.4
    container_name: sales-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_db
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: sales_pass
    ports:
      - "3306:3306"
    volumes:
      - sales-db-data:/var/lib/mysql
    networks:
      - microservices-net

  stock-microservice:
    build: ./inventory-ms
    container_name: stock-microservice
    depends_on:
      - stock-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://stock-database:3306/stock_db
      SPRING_DATASOURCE_USERNAME: stock_user
      SPRING_DATASOURCE_PASSWORD: stock_pass
      RABBITMQ_ADDRESS: ${RABBITMQ_ADDRESS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - "8081:8080"
    networks:
      - microservices-net

  sales-microservice:
    build: ./sales-ms
    container_name: sales-microservice
    depends_on:
      - sales-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sales-database:3306/sales_db
      SPRING_DATASOURCE_USERNAME: sales_user
      SPRING_DATASOURCE_PASSWORD: sales_pass
      RABBITMQ_ADDRESS: ${RABBITMQ_ADDRESS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - "8082:8080"
    networks:
      - microservices-net

  eureka-server:
    build: ./eureka-discovery-service
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - microservices-net

volumes:
  stock-db-data:
  sales-db-data:

networks:
  microservices-net:
    driver: bridge
